# -*- coding: utf-8 -*-
"""SimulasiMomentum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZLRn5R6vUrUgV7UaUJ66UWhXl3o_3zl

## UAS Berpikir Komputasi

Nama : Hilda Pertima

NIM : 06111282227016

#**MOMENTUM**

Momentum adalah besaran vektor dalam fisika yang menggambarkan "kuantitas gerak" suatu benda. Karena merupakan besaran vektor, momentum memiliki besar (nilai) dan arah, yang sama dengan arah kecepatan benda.
Secara matematis, momentum didefinisikan sebagai:

$p = m.v$

Berdasarkan rumus diatas momentum berbanding lurus dengan massa dan kecepatan, artinya semakin besar massa atau kecepatan suatu benda, semakin besar pula momentum yang dimilikinya. Sehingga benda yang lebih berat atau bergerak lebih cepat akan lebih sulit dihentikan atau diubah arah geraknya. Konsep ini sangat penting dalam menganalisis interaksi benda, seperti tumbukan, karena dalam sistem terisolasi momentum total selalu kekal, sesuai dengan hukum kekekalan momentum.\
"""

import numpy as np
import matplotlib.pyplot as plt

# Massa tetap
m = 5  # kg

# Rentang kecepatan
kecepatan = np.linspace(0, 10, 50)

# Hitung momentum
momentum = m * kecepatan

plt.figure(figsize=(8,5))
plt.plot(kecepatan, momentum, linewidth=3)
plt.xlabel("Kecepatan (m/s)")
plt.ylabel("Momentum (kg·m/s)")
plt.title("Grafik Momentum terhadap Kecepatan (m = 5 kg)")
plt.grid(True, alpha=0.3)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Kecepatan tetap
v = 10  # m/s

# Rentang massa
massa = np.linspace(1, 10, 50)

# Hitung momentum
momentum = massa * v

plt.figure(figsize=(8,5))
plt.plot(massa, momentum, linewidth=3)
plt.xlabel("Massa (kg)")
plt.ylabel("Momentum (kg·m/s)")
plt.title("Grafik Momentum terhadap Massa (v = 10 m/s)")
plt.grid(True, alpha=0.3)
plt.show()

"""## **Tumbukan**

Ketika membahas soal momentum, kita juga tidak terlepas dari pembahasan tentang tumbukan. Tumbukan adalah interaksi dua buah benda atau lebih yang saling bertukar gaya dalam selang waktu tertentu dan memenuhi hukum kekekalan momentum.

Hukum kekekalan momentum berbunyi:

“Jika tidak ada gaya luar yang bekerja pada sistem, maka momentum sebuah sistem akan selalu konstan.”

Benda yang saling bertabrakan akan mengalami tumbukan yang jenisnya berbeda-beda tergantung dari kondisinya. Jenis-jenis tumbukan ini dibedakan berdasarkan perubahan energi yang terjadi.

### Tumbukan Lenting Sempurna

Tumbukan lenting sempurna adalah jenis tumbukan di mana momentum total dan energi kinetik total sistem kedua benda tetap. Artinya tidak ada energi yang hilang menjadi bentuk lain seperti panas, bunyi, atau deformasi. Secara matematis, ini dapat dinyatakan dengan rumus:

1. Hukum Kekekalan Momentum Linear:

$m_1v_1 + m_2v_2 = m_1v_1^` + m_2v_2^`$

2. Hukum Kekekalan Energi Kinetik

$\frac{1}{2} m_1v_1^2 + \frac{1}{2} m_2v_2^2 = \frac{1}{2} m_1v_1'^2 + m_2v_2'^2$

di mana $m_1$, $m_2$ adalah massa benda, $v_1$, $v_2$adalah kecepatan sebelum tumbukan, dan $v_1'$, $v_2'$ adalah kecepatan setelah tumbukan.


Adapun ciri-ciri dari tumbukan lenting sempurna yaitu memiliki energi kinetik dan momentum yang kekal atau memiliki nilai yang sama saat sebelum tumbukan dan setelah tumbukan. Serta memiliki nilai koefisien restitusi $(e) = 1$. Tumbukan ini mencerminkan karakteristik ideal yang umumnya hanya terjadi pada benda-benda sangat elastis (seperti partikel atom atau bola baja pada permukaan keras).
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
m1 = 2.0
m2 = 1.5

v1 = 3.0
v2 = -2.0

x1 = -10.0
x2 = 10.0

dt = 0.05

Rumus_Tumbukan_lenting_sempurna = "m1*v1 + m2*v2 = m1*v1_akhir + m2*v2_akhir"

def lenting_sempurna(m1, m2, v1, v2):
    v1_akhir = (m1 - m2) / (m1 + m2) * v1 + (2 * m2) / (m1 + m2) * v2
    v2_akhir = (2 * m1) / (m1 + m2) * v1 + (m2 - m1) / (m1 + m2) * v2
    return v1_akhir, v2_akhir

v1_akhir, v2_akhir = lenting_sempurna(m1, m2, v1, v2)

# Sebelum tumbukan
p1_awal = m1 * v1
p2_awal = m2 * v2
p_total_awal = p1_awal + p2_awal

Ek1_awal = 0.5 * m1 * v1**2
Ek2_awal = 0.5 * m2 * v2**2

# Sesudah tumbukan
p1_akhir = m1 * v1_akhir
p2_akhir = m2 * v2_akhir
p_total_akhir = p1_akhir + p2_akhir

Ek1_akhir = 0.5 * m1 * v1_akhir**2
Ek2_akhir = 0.5 * m2 * v2_akhir**2

fig, ax = plt.subplots(figsize=(11, 5))
ax.set_xlim(-12, 12)
ax.set_ylim(-3, 3)
ax.set_title("Animasi Tumbukan Lenting Sempurna")
ax.set_xlabel("Posisi (m)")

obj1, = ax.plot([], [], 'o', ms=20, color='blue', label="Benda 1")
obj2, = ax.plot([], [], 'o', ms=20, color='red', label="Benda 2")
ax.legend()

info_text = ax.text(-11, 2.3, "", fontsize=9, va="top", family="monospace")

tumbukan = False

def update(frame):
    global x1, x2, v1, v2, tumbukan

    if not tumbukan:
        x1_new = x1 + v1 * dt
        x2_new = x2 + v2 * dt

        # Deteksi tumbukan
        if x1_new >= x2_new:
            tumbukan = True
            x1 = x2  # posisi saat kontak
        else:
            x1 = x1_new
            x2 = x2_new

        status = "SEBELUM TUMBUKAN"
        v1_show, v2_show = v1, v2
        p1, p2 = p1_awal, p2_awal
        Ek1, Ek2 = Ek1_awal, Ek2_awal

    else:
        x1 += v1_akhir * dt
        x2 += v2_akhir * dt

        status = "SESUDAH TUMBUKAN"
        v1_show, v2_show = v1_akhir, v2_akhir
        p1, p2 = p1_akhir, p2_akhir
        Ek1, Ek2 = Ek1_akhir, Ek2_akhir

    obj1.set_data([x1], [0])
    obj2.set_data([x2], [0])

    info_text.set_text(
        f"{status}\n"
        f"---------------------------\n"
        f"M1 = {m1} kg   |  M2 = {m2} kg\n"
        f"v1 = {v1_show:.2f} m/s | v2 = {v2_show:.2f} m/s\n"
        f"p1 = {p1:.2f}  kg·m/s | p2 = {p2:.2f} kg·m/s\n"
        f"Ek1 = {Ek1:.2f} J      | Ek2 = {Ek2:.2f} J\n"
        f"p total awal  = {p_total_awal:.3f} kg·m/s | p total akhir = {p_total_akhir:.3f} kg·m/s\n"
    )

    return obj1, obj2, info_text

anim = FuncAnimation(fig, update, frames=250, interval=40, blit=True)
plt.close(fig)
HTML(anim.to_jshtml())

"""## Tumbukan Lenting Sebagian

Tumbukan lenting sebagian adalah jenis tumbukan di mana momentum total sistem kekal, tetapi energi kinetik total tidak kekal—artinya sebagian energi kinetik hilang dan berubah menjadi bentuk energi lain, seperti panas, bunyi atau deformasi. Secara matematis, ini dapat dinyatakan dengan rumus:

1. Hukum Kekekalan Momentum Linear:

$m_1v_1 + m_2v_2 = m_1v_1^` + m_2v_2^`$

2. Hukum Kekekalan Energi Kinetik

$\frac{1}{2} m_1v_1^2 + \frac{1}{2} m_2v_2^2 = \frac{1}{2} m_1v_1'^2 + m_2v_2'^2$

Ciri utama tumbukan lenting sebagian adalah koefisien restitusi $e$ yang nilainya berada diantara 0 dan 1:

$0 < e < 1$

Koefisien restitusi mengukur tingkat kelentingan tumbukan, dihitung dari perbandingan kecepatan relatif setelah dan sebelum tumbukan:

$e =-\frac{v_1' - v_2'}{v_1 - v_2}$

Semakin kecil nilai $e$, semakin tidak lenting tumbukannya. Pada tumbukan ini hukum kekekalan momentum masih berlaku. Namun, energi kinetiknya tidak kekal yang menyebabkan energi kinetik setelah mengalami tumbukkan akan jadi lebih kecil dari sebelum tumbukan.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
m1 = 2.0
m2 = 1.5

v1 = 3.0
v2 = -2.0

x1 = -10.0
x2 = 10.0

dt = 0.05
e = 0.6  # koefisien restitusi (0 < e < 1)

Rumus_Tumbukan_lenting_sebagian = "m1*v1 + m2*v2 = m1*v1_akhir + m2*v2_akhir"
Rumus_Resitusi = "- (v1_akhir - V2_akhir)/(v1 - v2)"

def lenting_sebagian(m1, m2, v1, v2, e):
    # Kecepatan akhir berdasarkan kekekalan momentum + definisi koefisien restitusi
    v1_akhir = (m1*v1 + m2*v2 - m2*e*(v1 - v2)) / (m1 + m2)
    v2_akhir = (m1*v1 + m2*v2 + m1*e*(v1 - v2)) / (m1 + m2)
    return v1_akhir, v2_akhir

v1_akhir, v2_akhir = lenting_sebagian(m1, m2, v1, v2, e)

# Sebelum tumbukan
p1_awal = m1 * v1
p2_awal = m2 * v2
p_total_awal = p1_awal + p2_awal

Ek1_awal = 0.5 * m1 * v1**2
Ek2_awal = 0.5 * m2 * v2**2

# Sesudah tumbukan
p1_akhir = m1 * v1_akhir
p2_akhir = m2 * v2_akhir
p_total_akhir = p1_akhir + p2_akhir

Ek1_akhir = 0.5 * m1 * v1_akhir**2
Ek2_akhir = 0.5 * m2 * v2_akhir**2

fig, ax = plt.subplots(figsize=(11, 5))
ax.set_xlim(-12, 12)
ax.set_ylim(-3, 3)
ax.set_title("Animasi Tumbukan Lenting Sebagian (e = {:.1f})".format(e))
ax.set_xlabel("Posisi (m)")

obj1, = ax.plot([], [], 'o', ms=20, color='blue', label="Benda 1")
obj2, = ax.plot([], [], 'o', ms=20, color='red', label="Benda 2")
ax.legend()

info_text = ax.text(-11, 2.3, "", fontsize=9, va="top", family="monospace")

tumbukan = False

def update(frame):
    global x1, x2, v1, v2, tumbukan

    if not tumbukan:
        x1_new = x1 + v1 * dt
        x2_new = x2 + v2 * dt

        if x1_new >= x2_new:
            tumbukan = True
            x1 = x2
        else:
            x1 = x1_new
            x2 = x2_new

        status = "SEBELUM TUMBUKAN"
        v1_show, v2_show = v1, v2
        p1, p2 = p1_awal, p2_awal
        Ek1, Ek2 = Ek1_awal, Ek2_awal

    else:
        x1 += v1_akhir * dt
        x2 += v2_akhir * dt

        status = "SESUDAH TUMBUKAN"
        v1_show, v2_show = v1_akhir, v2_akhir
        p1 = p1_akhir
        p2 = p2_akhir
        Ek1 = Ek1_akhir
        Ek2 = Ek2_akhir

    obj1.set_data([x1], [0])
    obj2.set_data([x2], [0])

    info_text.set_text(
        f"{status}\n"
        f"---------------------------\n"
        f"M1 = {m1} kg   |  M2 = {m2} kg\n"
        f"v1 = {v1_show:.2f} m/s | v2 = {v2_show:.2f} m/s\n"
        f"p1 = {p1:.2f}  kg·m/s | p2 = {p2:.2f} kg·m/s\n"
        f"Ek1 = {Ek1:.2f} J      | Ek2 = {Ek2:.2f} J\n"
        f"p total awal  = {p_total_before:.3f} kg·m/s | p total akhir = {p_total_after:.3f} kg·m/s\n"
        f"Ek total awal = {Ek_total_before:.3f} J     | Ek total akhir = {Ek_total_after:.3f} J"
    )

    return obj1, obj2, info_text


anim = FuncAnimation(fig, update, frames=250, interval=40, blit=True)
plt.close(fig)
HTML(anim.to_jshtml())

"""## Tumbukan Tidak Lenting Sempurna

Tumbukan tidak lenting sempurna adalah jenis tumbukan di mana dua benda yang bertabrakan akan menyatu dan bergerak bersama setelah tumbukan, kehilangan sebagian energi kinetiknya (berubah jadi panas/bunyi) membuat nilai nya menjadi lebih kecil dari sebelum tumbukan, namun hukum kekekalan momentum total tetap berlaku, dengan nilai koefisien restitusi $(e)$ sama dengan nol $(e=0)$.

Rumus matematis:

$m_1v_1 + m_2v_2 = (m_1   + _2)v'$

Tumbukan ini terjadi apabila salah satu benda memiliki massa dan kecepatan yang jauh lebih besar dibandingkan massa dan kecepatan benda lainnya, sehingga benda lainnya yang bermassa dan berkecepatan kecil akan ikut terbawa.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
m1 = 2.0
m2 = 1.5

v1 = 3.0
v2 = -2.0

x1 = -10.0
x2 = 10.0

dt = 0.05

v_final = (m1 * v1 + m2 * v2) / (m1 + m2)

# Sebelum tumbukan
p1_awal = m1 * v1
p2_awal = m2 * v2
p_total_awal = p1_awal + p2_awal

Ek1_awal = 0.5 * m1 * v1**2
Ek2_awal = 0.5 * m2 * v2**2
Ek_total_awal = Ek1_awal + Ek2_awal

# Sesudah tumbukan
p1_akhir = m1 * v_final
p2_akhir = m2 * v_final
p_total_akhir = p1_akhir + p2_akhir

Ek1_akhir = 0.5 * m1 * v_final**2
Ek2_akhir = 0.5 * m2 * v_final**2
Ek_total_akhir = Ek1_akhir + Ek2_akhir

fig, ax = plt.subplots(figsize=(11, 5))
ax.set_xlim(-12, 12)
ax.set_ylim(-3, 3)
ax.set_title("Animasi Tumbukan Tidak Lenting Sempurna")
ax.set_xlabel("Posisi (m)")

obj1, = ax.plot([], [], 'o', ms=20, color='blue', label="Benda 1")
obj2, = ax.plot([], [], 'o', ms=20, color='red', label="Benda 2")
ax.legend()

info_text = ax.text(-11, 2.3, "", fontsize=9, va="top", family="monospace")
tumbukan = False

def update(frame):
    global x1, x2, v1, v2, tumbukan

    if not tumbukan:
        x1_new = x1 + v1 * dt
        x2_new = x2 + v2 * dt

        if x1_new >= x2_new:
            tumbukan = True
            x1 = x2 = (x1_new + x2_new) / 2.0  # <-- diperbaiki: tambahkan 2.0
        else:
            x1 = x1_new
            x2 = x2_new

        status = "SEBELUM TUMBUKAN"
        v1_show, v2_show = v1, v2
        p1, p2 = p1_awal, p2_awal
        Ek1, Ek2 = Ek1_awal, Ek2_awal

    else:
        x1 += v_final * dt
        x2 += v_final * dt

        status = "SESUDAH TUMBUKAN"
        v1_show = v2_show = v_final
        p1, p2 = p1_akhir, p2_akhir
        Ek1, Ek2 = Ek1_akhir, Ek2_akhir

    obj1.set_data([x1], [0])
    obj2.set_data([x2], [0])

    info_text.set_text(
        f"{status}\n"
        f"---------------------------\n"
        f"M1 = {m1} kg   |  M2 = {m2} kg\n"
        f"v1 = {v1_show:.2f} m/s | v2 = {v2_show:.2f} m/s\n"
        f"p1 = {p1:.2f}  kg·m/s | p2 = {p2:.2f} kg·m/s\n"
        f"Ek1 = {Ek1:.2f} J      | Ek2 = {Ek2:.2f} J\n"
        f"p total awal  = {p_total_awal:.3f} kg·m/s | p total akhir = {p_total_akhir:.3f} kg·m/s\n"
        f"Ek total awal = {Ek_total_awal:.3f} J     | Ek total akhir = {Ek_total_akhir:.3f} J"
    )

    return obj1, obj2, info_text

anim = FuncAnimation(fig, update, frames=250, interval=40, blit=True)
plt.close(fig)
HTML(anim.to_jshtml())

"""# KESIMPULAN

Momentum linear selalu kekal dalam sistem tertutup yang tidak dikenai gaya luar, baik pada tumbukan lenting sempurna maupun tidak lenting. Sebaliknya, energi kinetik hanya kekal pada tumbukan lenting sempurna; pada tumbukan lenting sebagian maupun tidak lenting sempurna, sebagian energi hilang dan berubah menjadi bentuk lain seperti panas, bunyi, atau deformasi. Tingkat kelentingan tumbukan ditentukan oleh koefisien restitusi $(e)$, di mana (e = 1) menunjukkan tumbukan lenting sempurna, (0 < e < 1) menunjukan tumbukan lenting sebagian, dan (e = 0) menunjukkan tumbukan tidak lenting sempurna di mana kedua benda menyatu setelah tumbukan. Simulasi numerik memudahkan visualisasi perubahan momentum, kecepatan, dan energi kinetik sebelum dan sesudah tumbukan, sehingga konsep tumbukan dapat dipahami secara intuitif.

"""

